openapi: 3.0.0
info:
  title: Voice Recipe API
  description: API для Voice Recipe.
  version: 1.0.0-oas3
components:
  schemas:
    MarksDto:
      type: object
      required:
        - recipe_id
        - user_id
        - mark
      properties:
        id:
          type: integer
          format: int64
          example: 30
        user_id:
          type: string
          maxLength: 32
          nullable: false
          example: AFEEF463FEDFFEDD
        recipe_id:
          $ref: '#/components/schemas/IdDto'
        mark:
          type: integer
          format: int32
          nullable: true
          example: 5
    IdDto:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          nullable: false
          example: 5234653
          
          
          
paths:
 /recipe:
      post:
        tags:
          - Необходимые
        summary: Добавить рецепт.
        description: Добавляет рецепт. Для рецепта медиа обязательно, для шагов - нет. Если указанных единиц измерения и ингредиентов нет, они добавляются сервером. Единицы измерения и ингредиенты хранятся в нижнем регистре вне зависимости от переданного вида.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'
        responses:
          "200":
            description: Рецепт был добавлен.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/IdDto'
          "400":
            description: Некорректный формат запроса или данные неверны.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 400,
                        "message": "Validation Failed"
                      }
  /recipe/{id}:
      get:
        tags:
          - Возможные
        summary: Поиск рецепта.
        description: Возвращает рецепт со всеми потрахами.
        parameters:
        - description: Идентификатор рецепта.
          in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          example: 1234
        responses:
          "200":
            description: Информация о рецепте.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RecipeDto'
             
          "400":
            description: Некорректный формат запроса.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 400,
                        "message": "Validation Failed"
                      }
          "404":
            description: Рецепт не найден.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 400,
                        "message": "Recipe not found"
                      }
      put:
        tags:
          - Необходимые
        summary: Обновить рецепт.
        description: Обновляет рецепт. Структура как в добавлении рецепта.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'
        responses:
          "200":
            description: Рецепт был обновлён.
            content: 
              application/json:
                schema:
                  $ref: '#/components/schemas/IdDto'
          "400":
            description: Некорректный формат запроса или данные неверны.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 400,
                        "message": "Validation Failed"
                      }
          "404":
            description: Рецепт не найден.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 400,
                        "message": "Recipe not found"
                      }

  /recipe/search/{name}:
      get:
        tags:
          - Необходимые
        summary: Поиск рецептов.
        description: Возвращает массив рецептов, количество определяется сервером. НЕ может вернуть пустой массив (вернет 404). Планируется использовать поиск подстроки.
        parameters:
        - description: Первые буквы, по которым идет поиск рецепта.
          in: path
          name: name
          required: true
          schema:
            type: string
            maxLength: 128
          example: "бо"
        - description: Лимит количества возвращаемых рецептов. Должен быть больше нуля.
          in: query
          name: limit
          required: false
          schema:
            type: integer
          example: 5
        responses:
          "200":
            description: Рецепты, в названии которых есть вхождение name.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/RecipeDto'
             
          "400":
            description: Некорректный формат запроса.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 400,
                        "message": "Validation Failed"
                      }
          "404":
            description: Рецепт не найден.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  response:
                    value: |-
                      {
                        "code": 404,
                        "message": "Recipe not found"
                      }
 
